version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: examplepassword
    ports:
      - 5432:5432